---
services:
  kcptun-client:
    command: ["/usr/local/bin/client", "-c", "/etc/kcptun.json"]
    image: docker.io/yaekee/kcptun-client:${KCPTUN_VERSION}
    restart: always
    volumes:
      - "./kcptun-client.json:/etc/kcptun.json"

  sslocal-rust:
    image: ghcr.io/shadowsocks/sslocal-rust:${SHADOWSOCKS_RUST_VERSION}
    ports:
      - "1080:1080/tcp"
    restart: always
    volumes:
      - "./ss-local.json:/etc/shadowsocks-rust/config.json"
