services:
  kcptun-server:
    command: ["/usr/local/bin/server", "-c", "/etc/kcptun.json"]
    image: docker.io/yaekee/kcptun-server:${KCPTUN_VERSION}
    ports:
      - 12948:12948/tcp
      - ${KCPTUN_PORT}:29900/udp
    restart: always
    volumes:
      - "./kcptun-server.json:/etc/kcptun.json"

  ssserver:
    image: ghcr.io/shadowsocks/ssserver-rust:${SHADOWSOCKS_RUST_VERSION}
    ports:
      - "${SHADOWSOCKS_PORT}:8388/tcp"
      - "${SHADOWSOCKS_PORT}:8388/udp"
    restart: always
    volumes:
      - "./ss-server.json:/etc/shadowsocks-rust/config.json"
