version: "3"

services:
  client:
    image: docker.io/teddysun/v2ray:${V2RAY_IMAGE_VERSION}
    ports:
      - 1080:1080
      - 1081:1081
    restart: always
    volumes:
      - "./config.json:/etc/v2ray/config.json"

  client-mkcp:
    image: docker.io/teddysun/v2ray:${V2RAY_IMAGE_VERSION}
    ports:
      - 1090:1090
      - 1091:1091
    restart: always
    volumes:
      - "./config-mkcp.json:/etc/v2ray/config.json"
